version: '3.5'

services:
  db:
    image: postgres:16.2-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U postgres
      interval: 1s
      timeout: 3s
      retries: 30

  database_setup:
    restart: "no"
    build:
      context: .
      dockerfile: rinha_api/Dockerfile
    command: bundle exec rails db:prepare
    depends_on:
      db:
        condition: service_healthy
    environment:
      APP_NAME: RinhaAPI01
      DB_HOST: db

  load_balancer:
    restart: always
    image: nginx:latest
    ports:
      - "9999:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api_instance_01
      - api_instance_02

  api_instance_01:
    restart: always
    build:
      context: .
      dockerfile: rinha_api/Dockerfile
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3001:3000"
    depends_on:
      - database_setup
    environment:
      APP_NAME: RinhaAPI01
      DB_HOST: db

  api_instance_02:
    restart: always
    build:
      context: .
      dockerfile: rinha_api/Dockerfile
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3002:3000"
    depends_on:
      - database_setup
    environment:
      APP_NAME: RinhaAPI02
      DB_HOST: db
