
default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DB_HOST") { "localhost" }  %>
  port: 5432
  username: postgres
  password: password
  database: rinha_database
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default

test:
  <<: *default
  database: rinha_database_test

production:
  <<: *default
